name: WillAirDrop
main: me.enot.willairdrop.WillAirDrop
version: 0.2.1
author: MiMiMiEnot
api-version: 1.13

softdepend:
  - HolographicDisplays
  - PlaceholderAPI

commands:
  airdrop:
    description: ""